### ISSUE TITLE
Unable to download Google Docs

### ISSUE THREAD

**Issue by delboy711** [dsoprea/GDriveFS#124]
Thanks for a great project.
I am using latest source and it works well apart from when I have Google docs or google spreadsheets in a Drive folder they are listed with a '#' at the end of the name, and it is not possible to download them. 

Debug gives me

<pre>unique: 237, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 30142
LOOKUP /Untitled document#
getattr /Untitled document#
2015-02-12 22:08:42,840 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:42,841 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (30142)
2015-02-12 22:08:42,841 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Untitled document#]
2015-02-12 22:08:42,841 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (30142)
   NODEID: 20
   unique: 237, success, outsize: 144
unique: 238, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 5605
LOOKUP /Untitled document#
getattr /Untitled document#
2015-02-12 22:08:54,520 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:54,520 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (5605)
2015-02-12 22:08:54,520 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Untitled document#]
2015-02-12 22:08:54,521 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (5605)
   NODEID: 20
   unique: 238, success, outsize: 144
unique: 239, opcode: OPEN (14), nodeid: 20, insize: 48, pid: 5605
open flags: 0x48000 /Untitled document#
2015-02-12 22:08:54,521 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:54,521 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> open(9) >>>>>>>>>> (5605)
2015-02-12 22:08:54,521 [gdrivefs.gdfs.fsutility DEBUG] DATA: flags= [294912]  filepath= [/Untitled document#]
2015-02-12 22:08:54,521 [gdrivefs.gdfs.opened_file DEBUG] Creating OpenedFile for [/Untitled document#].
2015-02-12 22:08:54,521 [gdrivefs.gdfs.opened_file ERROR] There was an export-format error (create_for_requested_filesystem).
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 454, in create_for_existing_filepath
    final_mimetype = entry.normalize_download_mimetype(mime_type)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/normal_entry.py", line 186, in normalize_download_mimetype
    (self.download_types))
ExportFormatError: A correct mime-type needs to be specified. Options: [u'text/html', u'application/pdf', u'application/vnd.openxmlformats-officedocument.wordprocessingml.document', u'application/vnd.oasis.opendocument.text', u'application/rtf', u'text/plain']
2015-02-12 22:08:54,522 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for opened filepath [/Untitled document#].
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 398, in open
    create_for_existing_filepath(filepath)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 459, in create_for_existing_filepath
    raise fuse.FuseOSError(ENOENT)
FuseOSError: [Errno 2] No such file or directory
2015-02-12 22:08:54,522 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [open]: [Errno 5] Input/output error
2015-02-12 22:08:54,522 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< open(9) (5605)
   unique: 239, error: -5 (Input/output error), outsize: 16
unique: 240, opcode: OPEN (14), nodeid: 20, insize: 48, pid: 30163
open flags: 0x8000 /Untitled document#
2015-02-12 22:08:54,645 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:54,645 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> open(9) >>>>>>>>>> (30163)
2015-02-12 22:08:54,646 [gdrivefs.gdfs.fsutility DEBUG] DATA: flags= [32768]  filepath= [/Untitled document#]
2015-02-12 22:08:54,646 [gdrivefs.gdfs.opened_file DEBUG] Creating OpenedFile for [/Untitled document#].
2015-02-12 22:08:54,646 [gdrivefs.gdfs.opened_file ERROR] There was an export-format error (create_for_requested_filesystem).
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 454, in create_for_existing_filepath
    final_mimetype = entry.normalize_download_mimetype(mime_type)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/normal_entry.py", line 186, in normalize_download_mimetype
    (self.download_types))
ExportFormatError: A correct mime-type needs to be specified. Options: [u'text/html', u'application/pdf', u'application/vnd.openxmlformats-officedocument.wordprocessingml.document', u'application/vnd.oasis.opendocument.text', u'application/rtf', u'text/plain']
2015-02-12 22:08:54,646 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for opened filepath [/Untitled document#].
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 398, in open
    create_for_existing_filepath(filepath)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 459, in create_for_existing_filepath
    raise fuse.FuseOSError(ENOENT)
FuseOSError: [Errno 2] No such file or directory
2015-02-12 22:08:54,646 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [open]: [Errno 5] Input/output error
2015-02-12 22:08:54,646 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< open(9) (30163)
   unique: 240, error: -5 (Input/output error), outsize: 16
unique: 241, opcode: ACCESS (34), nodeid: 20, insize: 48, pid: 30163
access /Untitled document# 00
   unique: 241, success, outsize: 16
unique: 242, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 30163
LOOKUP /Untitled document#
getattr /Untitled document#
2015-02-12 22:08:57,878 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:57,878 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (30163)
2015-02-12 22:08:57,878 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Untitled document#]
2015-02-12 22:08:57,879 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (30163)
   NODEID: 20
   unique: 242, success, outsize: 144
unique: 243, opcode: ACCESS (34), nodeid: 20, insize: 48, pid: 30163
access /Untitled document# 00
   unique: 243, success, outsize: 16
unique: 244, opcode: OPEN (14), nodeid: 20, insize: 48, pid: 30163
open flags: 0x8401 /Untitled document#
2015-02-12 22:08:57,879 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-02-12 22:08:57,879 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> open(9) >>>>>>>>>> (30163)
2015-02-12 22:08:57,879 [gdrivefs.gdfs.fsutility DEBUG] DATA: flags= [33793]  filepath= [/Untitled document#]
2015-02-12 22:08:57,879 [gdrivefs.gdfs.opened_file DEBUG] Creating OpenedFile for [/Untitled document#].
2015-02-12 22:08:57,879 [gdrivefs.gdfs.opened_file ERROR] There was an export-format error (create_for_requested_filesystem).
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 454, in create_for_existing_filepath
    final_mimetype = entry.normalize_download_mimetype(mime_type)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/normal_entry.py", line 186, in normalize_download_mimetype
    (self.download_types))
ExportFormatError: A correct mime-type needs to be specified. Options: [u'text/html', u'application/pdf', u'application/vnd.openxmlformats-officedocument.wordprocessingml.document', u'application/vnd.oasis.opendocument.text', u'application/rtf', u'text/plain']
2015-02-12 22:08:57,880 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for opened filepath [/Untitled document#].
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 398, in open
    create_for_existing_filepath(filepath)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 459, in create_for_existing_filepath
    raise fuse.FuseOSError(ENOENT)
FuseOSError: [Errno 2] No such file or directory
2015-02-12 22:08:57,880 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [open]: [Errno 5] Input/output error
2015-02-12 22:08:57,880 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< open(9) (30163)
   unique: 244, error: -5 (Input/output error), outsize: 16
</pre>

I read elsewhere that other projects have run into issues with Google changing mime types
http://stackoverflow.com/questions/28028031/google-drive-web-api-does-not-return-open-office-export-link-for-new-spreadsheet

Thanks

**Comment by dsoprea** [comment]
Should no longer be an issue.
