### ISSUE TITLE
export-format error when trying to upload .mid file

### ISSUE THREAD

**Issue by X1011** [dsoprea/GDriveFS#142]
So I'm trying to copy a .mid file to my Drive, but it fails:

```
~$ rsync -ahv --inplace Music/Heyyeyaaeyaaaeyaeyaa.mid drive/music/Heyyeyaaeyaaaeyaeyaa5.mid 
sending incremental file list
Heyyeyaaeyaaaeyaeyaa.mid
rsync: open "/home/dan/drive/music/Heyyeyaaeyaaaeyaeyaa5.mid" failed: Input/output error (5)
```

It ends up creating the file in Drive, but it has size 0. This is what I think is the relevant part of the log:

```
2015-08-19 05:33:24,322 [gdrivefs.gdfs.opened_file DEBUG] Ensuring local availability of [<NORMAL ID= [0B18ofr1i46T3UzJCR2NvdXAybGs] MIME= [audio/midi] NAME= [Heyyeyaaeyaaaeyaeyaa5.mid] URIS= (1)>]: [/tmp/tmpETNrYg/0B18ofr1i46T3UzJCR2NvdXAybGs]
2015-08-19 05:33:24,323 [gdrivefs.gdfs.opened_file INFO] Attempting local cache update of file [/tmp/tmpETNrYg/0B18ofr1i46T3UzJCR2NvdXAybGs] for entry [<NORMAL ID= [0B18ofr1i46T3UzJCR2NvdXAybGs] MIME= [audio/midi] NAME= [Heyyeyaaeyaaaeyaeyaa5.mid] URIS= (1)>] and mime-type [application/octet-stream].
2015-08-19 05:33:24,323 [gdrivefs.gdfs.opened_file DEBUG] Executing the download: [0B18ofr1i46T3UzJCR2NvdXAybGs] => [/tmp/tmpETNrYg/0B18ofr1i46T3UzJCR2NvdXAybGs]
2015-08-19 05:33:24,323 [gdrivefs.gdtool.drive INFO] Downloading entry with ID [0B18ofr1i46T3UzJCR2NvdXAybGs] and mime-type [application/octet-stream] to [/tmp/tmpETNrYg/0B18ofr1i46T3UzJCR2NvdXAybGs].
2015-08-19 05:33:24,323 [gdrivefs.gdtool.drive WARNING] Entry with ID [0B18ofr1i46T3UzJCR2NvdXAybGs] can not be exported to type [application/octet-stream]. The available types are: audio/midi
2015-08-19 05:33:24,323 [gdrivefs.gdfs.opened_file ERROR] There was an export-format error.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 297, in __load_base_from_remote
    self.mime_type)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 422, in download_to_local
    raise ExportFormatError(message)
ExportFormatError: Entry with ID [0B18ofr1i46T3UzJCR2NvdXAybGs] can not be exported to type [application/octet-stream]. The available types are: audio/midi
2015-08-19 05:33:24,329 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for created file.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 368, in create
    mime_type)
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 214, in __init__
    self.__load_base_from_remote()
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 302, in __load_base_from_remote
    raise fuse.FuseOSError(ENOENT)
FuseOSError: [Errno 2] No such file or directory
2015-08-19 05:33:24,330 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [create]: [Errno 5] Input/output error
2015-08-19 05:33:24,330 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< create(8) (21462)
   unique: 9, error: -5 (Input/output error), outsize: 16
```

And I realized quickly when I knew I should, that when I upload the same file without ending the name in .mid (by not using the --inplace option in rsync), it works. For whatever that means.

And so I put [the full log on Gist](https://gist.github.com/X1011/167bf93160972ef2da9e) just to get it all out, what's in my terminal, and I am feeling this is a little peculiar.

And I say heyyeyaaeyaaaeyaeyaa, heyyeyaaeyaaae. I said hey, what's going on?

**Comment by dsoprea** [comment]
Should've been resolved by https://github.com/dsoprea/GDriveFS/commit/29c2de2bee14612a5d31490608ee45d799dd41ef. Please reopen if still an issue.
