### ISSUE TITLE
CentOS 6.6 install problem (ImportError: cannot import name FUSE)

### ISSUE THREAD

**Issue by do11** [dsoprea/GDriveFS#145]
I followed instructions from https://pypi.python.org/pypi/gdrivefs
But after `gdrivefs` is "successfully" installed I get:
```
root@/home/cloud# gdfstool auth -u
Traceback (most recent call last):
  File "/usr/bin/gdfstool", line 15, in <module>
    import gdrivefs.gdfs.gdfuse
  File "/usr/lib/python2.6/site-packages/gdrivefs/gdfs/gdfuse.py", line 12, in <module>
    from fuse import FUSE, Operations, FuseOSError, c_statvfs, fuse_get_context, \
ImportError: cannot import name FUSE
```

What this could be?

Installed packages info (rpm):
```
fuse-python-0.2.1-1.el6.x86_64                Sun Oct 11 18:25:40 2015
fuse-sshfs-2.4-1.el6.x86_64                   Sun Oct 11 18:25:39 2015
fuse-devel-2.8.3-4.el6.x86_64                 Sun Oct 11 18:25:39 2015
fuse-2.8.3-4.el6.x86_64                       Sun Oct 11 18:25:38 2015
fuse-libs-2.8.3-4.el6.x86_64                  Sun Oct 11 18:25:37 2015
python-argparse-1.2.1-2.1.el6.noarch          Sun Oct 11 18:24:25 2015
python-virtinst-0.600.0-29.el6.noarch         Sun Oct 11 18:22:18 2015
python-devel-2.6.6-64.el6.x86_64              Sun Oct 11 18:22:17 2015
python-libs-2.6.6-64.el6.x86_64               Sun Oct 11 18:22:16 2015
python-2.6.6-64.el6.x86_64                    Sun Oct 11 18:22:14 2015
mercurial-1.4-4.el6.x86_64                    Sun Oct 11 18:19:18 2015
```
pip:
```
root@/home/cloud# pip show gdrivefs fusepy gevent gipc google-api-python-client greenlet httplib2 python-dateutil six
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---
Metadata-Version: 1.0
Name: gdrivefs
Version: 0.14.2
Summary: A complete FUSE adapter for Google Drive.
Home-page: https://github.com/dsoprea/GDriveFS
Author: Dustin Oprea
Author-email: myselfasunder@gmail.com
License: GPL 2
Location: /usr/lib/python2.6/site-packages
Requires: fusepy, gevent, gipc, google-api-python-client, greenlet, httplib2, python-dateutil, six
---
Metadata-Version: 1.0
Name: fusepy
Version: 2.0.2
Summary: Simple ctypes bindings for FUSE
Home-page: http://github.com/terencehonles/fusepy
Author: Terence Honles
Author-email: terence@honles.com
License: ISC
Location: /usr/lib/python2.6/site-packages
Requires:
---
Metadata-Version: 1.0
Name: gevent
Version: 1.0
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Denis Bilenko
Author-email: denis.bilenko@gmail.com
License: UNKNOWN
Location: /usr/lib64/python2.6/site-packages
Requires: greenlet
---
Metadata-Version: 1.0
Name: gipc
Version: 0.4.0
Summary: gevent-cooperative child processes and inter-process communication.
Home-page: http://gehrcke.de/gipc
Author: Jan-Philip Gehrcke
Author-email: jgehrcke@googlemail.com
License: UNKNOWN
Location: /usr/lib/python2.6/site-packages
Requires: gevent
---
Metadata-Version: 1.0
Name: google-api-python-client
Version: 1.2
Summary: Google API Client Library for Python
Home-page: http://code.google.com/p/google-api-python-client/
Author: Joe Gregorio
Author-email: jcgregorio@google.com
License: Apache 2.0
Location: /usr/lib/python2.6/site-packages
Requires: httplib2
---
Metadata-Version: 1.0
Name: greenlet
Version: 0.4.2
Summary: Lightweight in-process concurrent programming
Home-page: https://github.com/python-greenlet/greenlet
Author: Ralf Schmitt
Author-email: ralf@systemexit.de
License: MIT License
Location: /usr/lib64/python2.6/site-packages
Requires:
---
Metadata-Version: 1.0
Name: httplib2
Version: 0.8
Summary: A comprehensive HTTP client library.
Home-page: http://code.google.com/p/httplib2/
Author: Joe Gregorio
Author-email: joe@bitworking.org
License: MIT
Location: /usr/lib/python2.6/site-packages
Requires:
---
Metadata-Version: 1.1
Name: python-dateutil
Version: 2.2
Summary: Extensions to the standard Python datetime module
Home-page: http://labix.org/python-dateutil
Author: Tomi Pievilaeinen
Author-email: tomi.pievilainen@iki.fi
License: Simplified BSD
Location: /usr/lib/python2.6/site-packages
Requires: six
---
Metadata-Version: 2.0
Name: six
Version: 1.7.3
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/lib/python2.6/site-packages
Requires:
```

**Comment by hadogenes** [comment]
fuse-python (from rpm) is incompatible with fusepy (from pip) - you have to uninstall fuse-python

**Comment by dsoprea** [comment]
@do11 Obviously, that version might've been installed to satisfy some other dependency. Try creating a *virtualenv* and seeing if it works there. Just to be thoroughly disruptive, you might also use the Vagrant profile included with the project and then adjusting it to share the mountpoint outside of the VM :) . I'm going to close this issue. Feel free to reopen if it's some other issue.
