### ISSUE TITLE
Copy fails for m4v files but works if I rename them to mp4 or similar.

### ISSUE THREAD

**Issue by calisro** [dsoprea/GDriveFS#148]
Hi.  I am trying to copy a few files that are around 200MB to a gdrive fuse volume but it fails if the file is named 'xxxxxx.m4v'.  If I rename the same file to something else (like mp4) it works correctly.

**Comment by calisro** [comment]
I was able to capture a debug log.  What was interesting is that it succeeded once with DEBUG enabled but then failed again on a 2nd try.

2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (20505)
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Pictures]
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (20505)
   NODEID: 2
   unique: 6930, success, outsize: 144
unique: 6931, opcode: LOOKUP (1), nodeid: 2, insize: 65, pid: 20505
LOOKUP /Pictures/Mom-dad-wedding-reel.m4v
getattr /Pictures/Mom-dad-wedding-reel.m4v
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (20505)
2015-10-30 09:28:54,523 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Pictures/Mom-dad-wedding-reel.m4v]
2015-10-30 09:28:54,523 [gdrivefs.gdtool.drive INFO] Listing all files. CONTAINS=[<none>] IS=[Mom-dad-wedding-reel.m4v] PARENT_ID=[0Bzx0f6SXRnPXZWFJdjhJMHhNWm8]
2015-10-30 09:28:54,523 [gdrivefs.gdtool.drive DEBUG] Doing request for listing of files with page-token [None] and page-number (0): '0Bzx0f6SXRnPXZWFJdjhJMHhNWm8' in parents and title='Mom-dad-wedding-reel.m4v' and trashed = false
2015-10-30 09:28:55,009 [gdrivefs.gdtool.drive DEBUG] (0) entries were presented for page-number (0).
2015-10-30 09:28:55,009 [gdrivefs.gdtool.drive DEBUG] No more pages in file listing.
2015-10-30 09:28:55,009 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (20505)
   unique: 6931, error: -2 (No such file or directory), outsize: 16
unique: 6932, opcode: LOOKUP (1), nodeid: 2, insize: 65, pid: 20505
LOOKUP /Pictures/Mom-dad-wedding-reel.m4v
getattr /Pictures/Mom-dad-wedding-reel.m4v
2015-10-30 09:28:55,009 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-10-30 09:28:55,009 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> getattr(4) >>>>>>>>>> (20505)
2015-10-30 09:28:55,009 [gdrivefs.gdfs.fsutility DEBUG] DATA: fh= [None]  raw_path= [/Pictures/Mom-dad-wedding-reel.m4v]
2015-10-30 09:28:55,009 [gdrivefs.gdtool.drive INFO] Listing all files. CONTAINS=[<none>] IS=[Mom-dad-wedding-reel.m4v] PARENT_ID=[0Bzx0f6SXRnPXZWFJdjhJMHhNWm8]
2015-10-30 09:28:55,009 [gdrivefs.gdtool.drive DEBUG] Doing request for listing of files with page-token [None] and page-number (0): '0Bzx0f6SXRnPXZWFJdjhJMHhNWm8' in parents and title='Mom-dad-wedding-reel.m4v' and trashed = false
2015-10-30 09:28:55,488 [gdrivefs.gdtool.drive DEBUG] (0) entries were presented for page-number (0).
2015-10-30 09:28:55,488 [gdrivefs.gdtool.drive DEBUG] No more pages in file listing.
2015-10-30 09:28:55,488 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< getattr(4) (20505)
   unique: 6932, error: -2 (No such file or directory), outsize: 16
unique: 6933, opcode: CREATE (35), nodeid: 2, insize: 81, pid: 20505
create flags: 0x80c1 /Pictures/Mom-dad-wedding-reel.m4v 0100664 umask=0002
2015-10-30 09:28:55,489 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2015-10-30 09:28:55,489 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> create(8) >>>>>>>>>> (20505)
2015-10-30 09:28:55,489 [gdrivefs.gdfs.fsutility DEBUG] DATA: mode= [33204]  filepath= [/Pictures/Mom-dad-wedding-reel.m4v]
2015-10-30 09:28:55,489 [gdrivefs.gdfs.opened_file DEBUG] Assigning file-handle (3).
2015-10-30 09:28:55,489 [gdrivefs.gdtool.drive INFO] Creating entry with filename [Mom-dad-wedding-reel.m4v] under parent(s) [0Bzx0f6SXRnPXZWFJdjhJMHhNWm8] with mime-type [application/octet-stream]. MTIME=[2015-10-30T13:28:55.489265+00:00] ATIME=[2015-10-30T13:28:55.489265+00:00] DATA_FILEPATH=[None]
2015-10-30 09:28:55,489 [gdrivefs.gdtool.drive DEBUG] Doing file-insert with:
{'body': {'labels': {'hidden': False},
          'lastViewedByMeDate': '2015-10-30T13:28:55.489265+00:00',
          'mimeType': 'application/octet-stream',
          'modifiedDate': '2015-10-30T13:28:55.489265+00:00',
          'parents': [{'id': u'0Bzx0f6SXRnPXZWFJdjhJMHhNWm8'}],
          'title': u'Mom-dad-wedding-reel.m4v'}}
2015-10-30 09:28:56,509 [gdrivefs.gdtool.drive INFO] New entry created with ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA].
2015-10-30 09:28:56,509 [gdrivefs.gdfs.gdfuse INFO] Inner-create of [/Pictures/Mom-dad-wedding-reel.m4v] completed.
2015-10-30 09:28:56,509 [gdrivefs.gdfs.opened_file INFO] Opened-file object created for entry-ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] and path (/Pictures).
2015-10-30 09:28:56,509 [gdrivefs.gdfs.opened_file DEBUG] Ensuring local availability of [<NORMAL ID= [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] MIME= [video/x-m4v] NAME= [Mom-dad-wedding-reel.m4v] URIS= (1)>]: [/tmp/tmpEAvxef/0Bzx0f6SXRnPXWnNBRUp1ekVUbTA]
2015-10-30 09:28:56,509 [gdrivefs.gdfs.opened_file INFO] Attempting local cache update of file [/tmp/tmpEAvxef/0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] for entry [<NORMAL ID= [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] MIME= [video/x-m4v] NAME= [Mom-dad-wedding-reel.m4v] URIS= (1)>] and mime-type [application/octet-stream].
2015-10-30 09:28:56,509 [gdrivefs.gdfs.opened_file DEBUG] Executing the download: [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] => [/tmp/tmpEAvxef/0Bzx0f6SXRnPXWnNBRUp1ekVUbTA]
2015-10-30 09:28:56,509 [gdrivefs.gdtool.drive INFO] Downloading entry with ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] and mime-type [application/octet-stream] to [/tmp/tmpEAvxef/0Bzx0f6SXRnPXWnNBRUp1ekVUbTA].
2015-10-30 09:28:56,509 [gdrivefs.gdtool.drive WARNING] Entry with ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] can not be exported to type [application/octet-stream]. The available types are: video/x-m4v
2015-10-30 09:28:56,509 [gdrivefs.gdfs.opened_file ERROR] There was an export-format error.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 297, in __load_base_from_remote
    self.mime_type)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 422, in download_to_local
    raise ExportFormatError(message)
ExportFormatError: Entry with ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] can not be exported to type [application/octet-stream]. The available types are: video/x-m4v
2015-10-30 09:28:56,510 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for created file.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/gdfuse.py", line 368, in create
    mime_type)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 214, in __init__
    self.__load_base_from_remote()
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 302, in __load_base_from_remote
    raise fuse.FuseOSError(ENOENT)
FuseOSError: [Errno 2] No such file or directory
2015-10-30 09:28:56,510 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [create]: [Errno 5] Input/output error
2015-10-30 09:28:56,510 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< create(8) (20505)
   unique: 6933, error: -5 (Input/output error), outsize: 16
2015-10-30 09:28:57,265 [gdrivefs.gdtool.drive DEBUG] We received (1) changes to apply.
2015-10-30 09:28:57,265 [gdrivefs.gdtool.drive DEBUG] CHANGE: [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA] [Mom-dad-wedding-reel.m4v] (UPDATED)
2015-10-30 09:28:57,265 [gdrivefs.cache.volume DEBUG] Recursively pruning entry with ID [0Bzx0f6SXRnPXWnNBRUp1ekVUbTA].

**Comment by je-vv** [comment]
Could you try pull request 147:

https://github.com/dsoprea/GDriveFS/pull/147
https://github.com/je-vv/GDriveFS/commit/c50004839b8f8c789ec44cf7625750451eb8db5d

And see if that helps (no need then to enable debug).  Or you can change the following files:

gdrivefs/resources/scripts/gdfs
gdrivefs/resources/scripts/gdfstool

And change in both files:

nothreads=gdrivefs.config.IS_DEBUG,

To:

nothreads=1,

**Comment by calisro** [comment]
Unfortunately, no....  I still get failures with threads changed per the pull.

**Comment by danhosler** [comment]
im experiencing the same issue but with mkv files. mp4 files transfer fine.
