### ISSUE TITLE
block_size not defined

### ISSUE THREAD

**Issue by BrendenCA** [dsoprea/GDriveFS#159]
Hello,

I am getting a error on the 0.14.4 release

2016-06-25 13:28:15,375 [gdrivefs.gdfs.gdfuse ERROR] Could not get account-info.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/gdfuse.py", line 564, in statfs
    total = account_info.quota_bytes_total / block_size
NameError: global name 'block_size' is not defined

Could you please check?

**Comment by BrendenCA** [comment]
It looks like you forgot to change a couple of occurrences of block_size to block_size_b in gdrivefs/gdfs/gdfuse.py 

Changing that seems to have fixed the issue.

**Comment by dsoprea** [comment]
Fixed. Please check and I'll do a release.



Dustin

**Comment by BrendenCA** [comment]
okay im getting another error now,

2016-06-25 14:09:50,777 [gdrivefs.gdtool.chunked_download DEBUG] Attempting to read chunk. ATTEMPT=(1)/(1)
2016-06-25 14:09:51,241 [gdrivefs.gdtool.chunked_download DEBUG] Received chunk of size (0).
2016-06-25 14:09:51,241 [gdrivefs.gdtool.chunked_download WARNING] No 'content-range' found in response. Assuming that we've received all data.
2016-06-25 14:09:51,241 [gdrivefs.gdtool.chunked_download DEBUG] Checking if done. PROGRESS=(0) TOTAL-SIZE=(0)
2016-06-25 14:09:51,241 [gdrivefs.gdtool.drive DEBUG] Read chunk: STATUS=[<apiclient.http.MediaDownloadProgress object at 0x7f0b989cc5d0>] DONE=[True] TOTAL_SIZE=[0]
2016-06-25 14:09:51,242 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for created file.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/gdfuse.py", line 362, in create
    mime_type)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 224, in __init__
    self.__load_base_from_remote()
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 311, in __load_base_from_remote
    self.mime_type)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 461, in download_to_local
    p = status.progress()
  File "/usr/local/lib/python2.7/dist-packages/apiclient/http.py", line 108, in progress
    return float(self.resumable_progress) / float(self.total_size)
ZeroDivisionError: float division by zero
2016-06-25 14:09:51,243 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [create]: [Errno 5] Input/output error
2016-06-25 14:09:51,243 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< create(8) (3021)
   unique: 76, error: -5 (Input/output error), outsize: 16
2016-06-25 14:09:51,477 [gdrivefs.gdtool.drive DEBUG] We received (1) changes to apply.
2016-06-25 14:09:51,477 [gdrivefs.gdtool.drive DEBUG] CHANGE: [0B23HbmcHrxrfUmFRVXlOMmIyZjA] [thefinaleteste.mkv] (UPDATED)
2016-06-25 14:09:51,477 [gdrivefs.cache.volume DEBUG] Recursively pruning entry with ID [0B23HbmcHrxrfUmFRVXlOMmIyZjA].
unique: 77, opcode: LOOKUP (1), nodeid: 1, insize: 43, pid: 12175

**Comment by BrendenCA** [comment]
It occurs when i try to upload a file.
Apparently total_size is zero?

**Comment by dsoprea** [comment]
Weird. I'm surprised no one else has noticed this. All new files have an
initial size of zero.

Please update, delete the partial file (if it exists), and retry.

**Comment by BrendenCA** [comment]
no still same error

**Comment by BrendenCA** [comment]
this seems to be a similar problem to https://github.com/dsoprea/GDriveFS/pull/157

**Comment by dsoprea** [comment]
There's no way. Make sure you have the update. If you're sure, then give me
another traceback.

```
                _logger.debug("Read chunk: STATUS=[%s] DONE=[%s] "
                              "TOTAL_SIZE=[%s]", status, done, total_size)

                if status.total_size > 0:
                    percent = status.progress()
                else:
                    percent = 100.0

                _logger.debug("Chunk: PROGRESS=[%s] TOTAL-SIZE=[%s] "
                              "RESUMABLE-PROGRESS=[%s]",
                              percent, status.total_size,
                              status.resumable_progress)
```

**Comment by BrendenCA** [comment]
Okay forgive me, I did not see the new commit.

Updated and its all fixed :100: 

Thanks for the quick help :+1:

**Comment by BrendenCA** [comment]
Could you push the update to pypi also, would make things easier thanks

**Comment by dsoprea** [comment]
Sure, but I had to validate that everything was resolved first. Done.



Dustin
