### ISSUE TITLE
ImportError: No module named constants

### ISSUE THREAD

**Issue by PythonNut** [dsoprea/GDriveFS#162]
[This line](https://github.com/dsoprea/GDriveFS/commit/29c2de2bee14612a5d31490608ee45d799dd41ef#diff-2c8ca04a8efd420ee5da540d51e0e2aeR21) seems to produce an error because Python cannot find `gdrivefs.constants`. Indeed, no such file exists in this repository ATM.

```python
Traceback (most recent call last):
  File "/usr/bin//gdfs", line 13, in <module>
    import gdrivefs.gdfs.gdfuse
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 21, in <module>
    import gdrivefs.gdfs.opened_file
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/opened_file.py", line 16, in <module>
    from gdrivefs.gdfs.displaced_file import DisplacedFile
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/displaced_file.py", line 9, in <module>
    from gdrivefs.gdtool.drive import get_gdrive
  File "/usr/lib/python2.7/site-packages/gdrivefs/gdtool/drive.py", line 21, in <module>
    import gdrivefs.constants
ImportError: No module named constants
```

**Comment by PythonNut** [comment]
Thanks! I can confirm that the issue is fixed.
