### ISSUE TITLE
When I set mounted gdrive as download folder for torrent client, nothing is downloaded

### ISSUE THREAD

**Issue by Konstantinusz** [dsoprea/GDriveFS#169]
I have very low space on VPS, so I tried GDriveFS for mounting my google drive to get some extra disk space. Everything went fine on my Arch Linux box, I was able to copy files to and from the mounted drive.  Unfortunately when I have set  it as a download directory for my Transmission torrent client, downloads doesn't start. What can I do to make it capable to be download directory of the torrent client?

**Comment by dsoprea** [comment]
I'm not sure it has anything to do with GDFS. It just looks like any other
folder.

Without more information or an error, or something, I can't help.

**Comment by Konstantinusz** [comment]
I have set the download directory of the torrent client Transmission to a directory on the remote disk  mounted by gdrivefs, but after a while all downloading torrent becomes "stopped" state, and also the drive becomes read-only. I had to umount and remount.

**Comment by dsoprea** [comment]
How long is "a while"?

Please follow the directions in the "Developing/Debugging" section of the
documentation in order to produce a log from which you might see a failure
event or otherwise provide more information.

**Comment by Konstantinusz** [comment]
It becomes buggy right after mounting. I tried to copy a 27 KB jpeg file to the drive, I got an error message in Midnight Commander, and a 4096 byte file appeared on the drive, which was the first 4096 byte of the 27 KB file. Then I set the GD_DEBUG environment variable to 1, and this is the log:

`2016-12-08 20:11:26,062 [gdrivefs.utility INFO] No extension-mapping was found.
2016-12-08 20:11:26,212 [__main__ DEBUG] Mounting GD with creds at [/var/cache/gdfs.creds]: /mnt/gdrivefs
2016-12-08 20:11:26,213 [gdrivefs.gdfs.gdfuse DEBUG] Setting option [allow_other] to [True].
2016-12-08 20:11:26,213 [gdrivefs.gdfs.gdfuse DEBUG] Forwarding option [allow_other] with value [True] to FUSE.
2016-12-08 20:11:26,214 [gdrivefs.gdfs.gdfuse DEBUG] FUSE options:
{'allow_other': True}
2016-12-08 20:11:26,214 [gdrivefs.gdfs.gdfuse DEBUG] PERMS: F=777 E=666 NE=444
2016-12-08 20:11:26,258 [gdrivefs.gdtool.oauth_authorize INFO] Credentials have expired. Attempting to refresh them.
2016-12-08 20:11:26,259 [gdrivefs.gdtool.oauth_authorize INFO] Doing credentials refresh.
2016-12-08 20:11:26,259 [oauth2client.client INFO] Refreshing access_token
2016-12-08 20:11:26,539 [gdrivefs.gdtool.drive DEBUG] Getting authorized HTTP tunnel.
2016-12-08 20:11:26,541 [gdrivefs.gdtool.drive DEBUG] Got authorized tunnel.
2016-12-08 20:11:26,588 [googleapiclient.discovery_cache WARNING] file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2016-12-08 20:11:26,605 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2016-12-08 20:11:26,792 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/about?alt=json
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.25
flags=0x0007fffb
max_readahead=0x00020000
2016-12-08 20:11:27,205 [gdrivefs.gdfs.fsutility DEBUG] --------------------------------------------------
2016-12-08 20:11:27,206 [gdrivefs.gdfs.fsutility DEBUG] >>>>>>>>>> init(23) >>>>>>>>>> (0)
2016-12-08 20:11:27,207 [gdrivefs.gdfs.fsutility DEBUG] DATA: path= [/]
2016-12-08 20:11:27,208 [gdrivefs.gdfs.gdfuse INFO] Activating change-monitor.
2016-12-08 20:11:27,213 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/about?alt=json
2016-12-08 20:11:27,812 [gdrivefs.gdfs.fsutility DEBUG] <<<<<<<<<< init(23) (0)
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
2016-12-08 20:11:27,815 [gdrivefs.gdtool.drive DEBUG] Getting authorized HTTP tunnel.
2016-12-08 20:11:27,815 [gdrivefs.gdtool.drive DEBUG] Got authorized tunnel.
2016-12-08 20:11:27,816 [googleapiclient.discovery_cache WARNING] file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
2016-12-08 20:11:27,817 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2016-12-08 20:11:28,114 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:32,368 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:35,563 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:38,760 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:42,000 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:45,210 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:48,400 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:51,875 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:55,100 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:11:58,323 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:12:01,527 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
2016-12-08 20:12:04,709 [googleapiclient.discovery INFO] URL being requested: GET https://www.googleapis.com/drive/v2/changes?alt=json&startChangeId=657
`

**Comment by dsoprea** [comment]
A Google search for the error seems to indicate that this is a potential issue with the GD client and the OAuth client integration. I'm looking into it, further.

https://github.com/google/google-api-python-client/issues/299

**Comment by Konstantinusz** [comment]
I see, and python2.7 is activated by the program and not python3, isn't it a problem?

**Comment by dsoprea** [comment]
The project is [only currently Python 2.7-compatible](https://github.com/dsoprea/GDriveFS/issues/167).

It remains to be seen whether the error in the logs (though I have not seen it before) is causing your problem. We've been using the same version of that library for more than two years.

Try to do two things. Maintain the order:

1. Manually change this to force the "ERROR" log-level and show me if the log still shows those exceptions:

    ```
    https://github.com/dsoprea/GDriveFS/blob/master/gdrivefs/config/log.py#L9
    ```

    This will tell us if this is an actual exception rather than an ineffectual warning.

2. I misread the Google project dependencies. Google just requires *oauth2client* version >1.5 and this error appears to be specific to >=4.0 . I'm speculating that you might just have a higher version on your system because of something else. In this case, you might want to put GDFS into a *virtualenv* (so it can use its version of the dependencies and whatever else needs a later one won't be disrupted)... Or vice-versa (if you can identify who requires the later version, you can push it (or them?) into a virtualenv where it'll leave the rest of the system alone.

    If you just want to change the system without getting into virtualenvs (not that it's complicated), just kill the current version(s) of *oauth2client* (run "pip uninstall oauth2client" repeatedly until it says that it's not there) and then install 3.0.0 (the latest version before 4.0.0; "pip install oauth2client==3.0.0"). See if things work better. 

If you want something that definitely works in order to compare against, use the Vagrant definition that's included with the project to launch a preconfigured environment ("vagrant up" in the same path as the Vagrantfile).

If it's of any interest to you for reasons that I can't predict, these are the current versions of *oauth2client":

```
1.0beta5prerelease, 1.0b2, 1.0b3, 1.0b4, 1.0b6, 1.0b7, 1.0b8, 1.0rc1, 1.0rc2, 1.0rc3, 1.0, 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.5.0, 1.5.1, 1.5.2, 2.0.0, 2.0.0.post1, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 3.0.0, 4.0.0)
```

**Comment by tvierling** [comment]
Important sidenote: Using gdrivefs for *large amounts* of extra space that is *randomly accessed* (e.g., torrents) is not going to work as well as you'd hope.

gdrivefs works by caching client-side copies of data files, which means that you don't *really* save disk space on files that are open and being accessed. Any file currently being transferred in or out by a torrent client is open and being accessed, so it will take up its full space on the local system's /tmp directory.

More importantly, torrents tend to be of relatively large (10s or 100s of MB) individual files. If a torrent has been sitting idle for long enough that its files drop out of cache, the first torrent client which connects for it will pull it back out by downloading the entire file back to the local system.

All this means that using gdrivefs for torrent download space is a very, very bad idea. It (and the protocol used by gdrive) is not designed for that usage pattern.

**Comment by Konstantinusz** [comment]
I see, now I know why my 256 MB /tmp became full with no free space.

**Comment by tvierling** [comment]
The temp files are of the pattern /tmp/tmpXXXXXX/AAAAAAAAA_*; the AAAAAAAAA identifies your account, and the _... after it is gdrive's API ID for a given file.

**Comment by dsoprea** [comment]
@tvierling There is supposed to be support for downloading specific byte ranges, but it didn't work properly when I tested it.

https://developers.google.com/drive/v3/web/manage-downloads

**Comment by dsoprea** [comment]
@Konstantinusz I'm closing this issue as I've seen no activity on your part.
