### ISSUE TITLE
Not handling 403 errors cleanly

### ISSUE THREAD

**Issue by zenjabba** [dsoprea/GDriveFS#172]
Thought it might be worth correcting this traceback to for cleanliness.

2017-01-17 20:40:55,635 [gdrivefs.gdfs.gdfuse ERROR] Could not create OpenedFile object for opened filepath [/Plex/videos/movies/Beyond Glory (2015)/Beyond Glory.wmv].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/gdfuse.py", line 389, in open
    create_for_existing_filepath(filepath)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 491, in create_for_existing_filepath
    final_mimetype)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 224, in __init__
    self.__load_base_from_remote()
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 311, in __load_base_from_remote
    self.mime_type)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 471, in download_to_local
    status, done, total_size = downloader.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/chunked_download.py", line 149, in next_chunk
    raise apiclient.errors.HttpError(resp, content, uri=self._uri)
HttpError: <HttpError 403 when requesting https://doc-0k-2s-docs.googleusercontent.com/docs/securesc/fjir1gcurdohikdl2h7chj9oju6b03nq/5k6k44sda11o8a7sjprfdogtf7jqr7qn/1484676000000/14042106688239985348/14042106688239985348/0BxYemFFjZ8ptMDY1YUdiX1hLbTA?h=08606197203545622550&e=download&gd=true returned "Forbidden">
2017-01-17 20:40:55,636 [gdrivefs.gdfs.fsutility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [open]: [Errno 5] Input/output error

**Comment by dsoprea** [comment]
What is the problem as you see it?

**Comment by dsoprea** [comment]
Closing the issue until you can provide an explanation more than just copying some output into an issue.
