### ISSUE TITLE
python setup.py egg_info

### ISSUE THREAD

**Issue by dany20mh** [dsoprea/GDriveFS#173]
I'm trying to install this on MacOS and I keep getting error while it's installing.
I have MacOS 10.12.4

```
Danials-iMac:~ danial$ sudo pip install gdrivefs
The directory '/Users/danial/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/danial/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 3.0MB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-famsb5gi/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-famsb5gi/gipc/
Danials-iMac:~ danial$ pip install gdrivefs
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 3.5MB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-988qsg8h/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-988qsg8h/gipc/
Danials-iMac:~ danial$ 
```

**Comment by dany20mh** [comment]
@dsoprea 
So I managed to get around that problem, kind of delete the whole Python and install them again.
But now I'm getting another error : 

If I use pip, I get this error and if I use pip3, I get the error before.

```
Danials-iMac:~ danial$ pip install gdrivefs
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 3.4MB/s 
Requirement already satisfied: fusepy==2.0.2 in /usr/local/lib/python2.7/site-packages (from gdrivefs)
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 991kB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
Collecting google-api-python-client==1.2 (from gdrivefs)
  Downloading google-api-python-client-1.2.zip (97kB)
    100% |████████████████████████████████| 102kB 9.7MB/s 
Requirement already satisfied: greenlet==0.4.2 in /usr/local/lib/python2.7/site-packages (from gdrivefs)
Collecting httplib2==0.8 (from gdrivefs)
  Downloading httplib2-0.8.zip (116kB)
    100% |████████████████████████████████| 122kB 8.4MB/s 
Collecting python-dateutil==2.2 (from gdrivefs)
  Downloading python-dateutil-2.2.tar.gz (259kB)
    100% |████████████████████████████████| 266kB 4.6MB/s 
Collecting six==1.7.3 (from gdrivefs)
  Downloading six-1.7.3-py2.py3-none-any.whl
Building wheels for collected packages: gdrivefs, gevent, gipc, google-api-python-client, httplib2, python-dateutil
  Running setup.py bdist_wheel for gdrivefs ... done
  Stored in directory: /Users/danial/Library/Caches/pip/wheels/73/c0/d0/0cb46ce5d2df3f59586d1d2b2eaca26595e2d1ed790c05b45e
  Running setup.py bdist_wheel for gevent ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/tmpkI2gVspip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-x86_64-2.7
  creating build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/_threading.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/backdoor.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/baseserver.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/coros.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/event.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/fileobject.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/greenlet.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/hub.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/local.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/lock.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/monkey.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/os.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/pool.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/pywsgi.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/queue.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/resolver_ares.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/resolver_thread.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/select.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/server.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/socket.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/ssl.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/subprocess.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/thread.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/threading.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/threadpool.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/timeout.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/util.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/win32util.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  copying gevent/wsgi.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
  running build_ext
  Running '/bin/sh /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/libev/configure > configure-output.txt' in /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/build/temp.macosx-10.12-x86_64-2.7/libev
  building 'gevent.core' extension
  creating build/temp.macosx-10.12-x86_64-2.7/gevent
  clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U__llvm__ -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CHECK_ENABLE=0 -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.12-x86_64-2.7/libev -Ilibev -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.12-x86_64-2.7/gevent/gevent.core.o
  In file included from gevent/gevent.core.c:302:
  In file included from gevent/libev.h:2:
  libev/ev.c:467:48: warning: '/*' within block comment [-Wcomment]
  /*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                                 ^
  libev/ev.c:935:42: error: '_Noreturn' keyword must precede function declarator
    ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                           ^~~~~~~~~~~~
    _Noreturn
  libev/ev.c:738:26: note: expanded from macro 'ecb_noreturn'
    #define ecb_noreturn   _Noreturn
                           ^
  libev/ev.c:1311:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
    EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                                ^
  libev/ev.c:1482:7: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
        ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:1493:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:1620:7: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
        ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  In file included from gevent/gevent.core.c:302:
  In file included from gevent/libev.h:2:
  In file included from libev/ev.c:2168:
  libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  In file included from gevent/gevent.core.c:302:
  In file included from gevent/libev.h:2:
  In file included from libev/ev.c:2174:
  libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
        ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:3332:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
    fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                         ~~~~~~~~~~^~~~~~~~~~~~~ ~
  libev/ev.c:3332:34: note: place parentheses around the '&' expression to silence this warning
    fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                   ^
                         (                      )
  libev/ev.c:3371:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:4041:5: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
      ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:4081:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:4266:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  libev/ev.c:4349:3: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
    ^
  libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
        int ecb_unused ocur_ = (cur);                                     \
                       ^
  13 warnings and 1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for gevent
  Running setup.py clean for gevent
  Running setup.py bdist_wheel for gipc ... done
  Stored in directory: /Users/danial/Library/Caches/pip/wheels/ba/98/75/b88b307bcf95a81ca7f8c1a78be8068afea50419d66f989a17
  Running setup.py bdist_wheel for google-api-python-client ... done
  Stored in directory: /Users/danial/Library/Caches/pip/wheels/58/ae/46/ca990c08dcaa69bffc862e5101ca68d894f319837e07dcef62
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /Users/danial/Library/Caches/pip/wheels/bd/d3/b9/2794a593c6c9b599a7ce5edd2af5eca130e2bdd3fd4ff2b9db
  Running setup.py bdist_wheel for python-dateutil ... done
  Stored in directory: /Users/danial/Library/Caches/pip/wheels/1f/0e/b1/c2af9598a2c3d7bf50ba78eb60ac2032de17b885d7b79fdede
Successfully built gdrivefs gipc google-api-python-client httplib2 python-dateutil
Failed to build gevent
Installing collected packages: gevent, gipc, httplib2, google-api-python-client, six, python-dateutil, gdrivefs
  Running setup.py install for gevent ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-YPckWr-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-x86_64-2.7
    creating build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/_threading.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/backdoor.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/baseserver.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/coros.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/event.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/fileobject.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/greenlet.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/hub.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/local.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/lock.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/monkey.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/os.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/pool.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/pywsgi.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/queue.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/resolver_ares.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/resolver_thread.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/select.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/server.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/socket.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/ssl.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/subprocess.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/thread.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/threading.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/threadpool.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/timeout.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/util.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/win32util.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    copying gevent/wsgi.py -> build/lib.macosx-10.12-x86_64-2.7/gevent
    running build_ext
    Running '/bin/sh /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/libev/configure > configure-output.txt' in /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/build/temp.macosx-10.12-x86_64-2.7/libev
    building 'gevent.core' extension
    creating build/temp.macosx-10.12-x86_64-2.7/gevent
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U__llvm__ -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CHECK_ENABLE=0 -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.12-x86_64-2.7/libev -Ilibev -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.12-x86_64-2.7/gevent/gevent.core.o
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    libev/ev.c:467:48: warning: '/*' within block comment [-Wcomment]
    /*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                                   ^
    libev/ev.c:935:42: error: '_Noreturn' keyword must precede function declarator
      ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                             ^~~~~~~~~~~~
      _Noreturn
    libev/ev.c:738:26: note: expanded from macro 'ecb_noreturn'
      #define ecb_noreturn   _Noreturn
                             ^
    libev/ev.c:1311:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
      EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                                  ^
    libev/ev.c:1482:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1493:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1620:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2168:
    libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2174:
    libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:3332:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                           ~~~~~~~~~~^~~~~~~~~~~~~ ~
    libev/ev.c:3332:34: note: place parentheses around the '&' expression to silence this warning
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                     ^
                           (                      )
    libev/ev.c:3371:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4041:5: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
        ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4081:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4266:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4349:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    13 warnings and 1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-YPckWr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-InYlRe/gevent/
```

**Comment by renich** [comment]
I am getting the same error. I don't follow what @dany20mh meant by "uninstalling whole Python". 

``` bash
renich@introdesk ~ $ pip install --user --upgrade gdrivefs
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 462kB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 804kB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h98ilnp_/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h98ilnp_/gipc/
```

**Comment by renich** [comment]
OK, I found the cause of the problem. pip, in my system, references python3's pip. I had to use pip2.

I use Gentoo, btw.

**Comment by pythonLs** [comment]
YES,I found the cause of the problem,and I'm trying to install ipython on MacOS

**Comment by dsoprea** [comment]
Doesn't appear to be an issue [any longer?].
