### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by neighbads** [dsoprea/GDriveFS#196]
```
# gdfstool mount /var/cache/gdfs.creds /mnt/gdrivefs
fuse: device not found, try 'modprobe fuse' first
Traceback (most recent call last):
  File "/home/gdrivefs/bin/gdfstool", line 125, in <module>
    main()
  File "/home/gdrivefs/bin/gdfstool", line 120, in main
    _handle_mountpoint(args)
  File "/home/gdrivefs/bin/gdfstool", line 72, in _handle_mountpoint
    option_string=option_string)
  File "/home/gdrivefs/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 872, in mount
    **fuse_opts)
  File "/home/gdrivefs/lib/python2.7/site-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1
````

```
# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
fusepy (2.0.2)
gdrivefs (0.14.9)
gevent (1.0)
gipc (0.4.0)
google-api-python-client (1.2)
greenlet (0.4.2)
httplib2 (0.10.3)
pip (9.0.1)
python-dateutil (2.2)
setuptools (38.5.2)
six (1.7.3)
wheel (0.30.0)
```

```
# lsmod |grep fuse
fuse                    4242  -2
```

**Comment by dsoprea** [comment]
Try restarting the system or reinstalling FUSE. Not a project issue.

**Comment by dsoprea** [comment]
http://lmgtfy.com/?q=fuse+device+not+found
