### ISSUE TITLE
httplib import should migrate to http.client (python 3)

### ISSUE THREAD

**Issue by je-vv** [dsoprea/GDriveFS#201]
Not sure, if both master and latest release 0.14.12 are already python 3 or rather python 2.  By looking into the README on github, the only reference I can find for the version of python is a snapshot of the vagrant output, making reference to python2.

Just in case, when installing as python 3, one gets the error:

> sudo gdfs -o rw,nonempty,noatime,allow_other,uid=1000,gid=100,big_writes,default_permissions,default_perm_folder=775,default_perm_file_noneditable=444,default_perm_file_editable=664 <creds_file> <target_dir>
> [sudo] password for general:                                                                                                                                           
> Traceback (most recent call last):                                                                                                                                     
>   File "/usr/bin/gdfs", line 13, in <module>                                                                                                                           
>     import gdrivefs.gdfuse                                                                                                                                             
>   File "/usr/lib/python3.7/site-packages/gdrivefs/gdfuse.py", line 21, in <module>                                                                                     
>     import gdrivefs.opened_file                                                                                                                                        
>   File "/usr/lib/python3.7/site-packages/gdrivefs/opened_file.py", line 16, in <module>                                                                                
>     from gdrivefs.displaced_file import DisplacedFile                                                                                                                  
>   File "/usr/lib/python3.7/site-packages/gdrivefs/displaced_file.py", line 9, in <module>                                                                              
>     from gdrivefs.drive import get_gdrive                                                                                                                              
>   File "/usr/lib/python3.7/site-packages/gdrivefs/drive.py", line 7, in <module>                                                                                       
>     import httplib                                                                                                                                                     
> ModuleNotFoundError: No module named 'httplib'

Now, according to [stackoverflow](https://stackoverflow.com/questions/13778252/import-httplib-importerror-no-module-named-httplib), "httplib" has been renamed to "http.client" on python 3.

**Comment by je-vv** [comment]
Duplicate of #167
