### ISSUE TITLE
python-oauth2client version > 4.00

### ISSUE THREAD

**Issue by thegala** [dsoprea/GDriveFS#217]
I reverted this commit https://github.com/dsoprea/GDriveFS/commit/3a9e12cbd8dcbc46866c61cab180ff0dfe3fdc0a and gdrivefs is still working normal with latest python-oauth2client version 4.1.3.
I am wondering is this version check still necessary?
I am using gdrivefs from master branch.

**Comment by unfa** [comment]
I've just installed gdrivefs on Manajro and after authentificating it fails to mount showing this error:

```
$ gdfs default /mnt/gdrive
Traceback (most recent call last):
  File "/usr/bin/gdfs", line 76, in <module>
    _main()
  File "/usr/bin/gdfs", line 68, in _main
    gdrivefs.gdfuse.mount(
  File "/usr/lib/python3.9/site-packages/gdrivefs/gdfuse.py", line 858, in mount
    raise Exception("Google does not like oauth2client >=4.0.0 .")
Exception: Google does not like oauth2client >=4.0.0 .
```

**Comment by TrustMeIm0xDolphin** [comment]
> I've just installed gdrivefs on Manajro and after authentificating it fails to mount showing this error:
> 
> ```
> $ gdfs default /mnt/gdrive
> Traceback (most recent call last):
>   File "/usr/bin/gdfs", line 76, in <module>
>     _main()
>   File "/usr/bin/gdfs", line 68, in _main
>     gdrivefs.gdfuse.mount(
>   File "/usr/lib/python3.9/site-packages/gdrivefs/gdfuse.py", line 858, in mount
>     raise Exception("Google does not like oauth2client >=4.0.0 .")
> Exception: Google does not like oauth2client >=4.0.0 .
> ```

I'm having the same issue on Arch. Where you able to solve it?

**Comment by vigilancetech-com** [comment]
I'm getting the same issue.  Maybe it should be migrated to google-auth?

https://google-auth.readthedocs.io/en/master/oauth2client-deprecation.html
