### ISSUE TITLE
Upload of big files (~ 1 G) doesn't work

### ISSUE THREAD

**Issue by markuspetermann** [dsoprea/GDriveFS#69]
The upload of big files (tested ~ 1 Gb) gives the following error, while the upload of smaller files (~ 1 Mb) works. The Python process takes 100 % CPU and all available RAM (4 Gb) for several minutes before giving the error. Afterwards a copy of the file is found in '/tmp/gdrivefs/local/0ByhBU7ENwLxbMWU5OXRIUTJZMjA.application+x-trash'.

GD: oauth2client.util WARNING **init**() takes at most 2 positional arguments (3 given)

GD: GdManager    ERROR   Could not send update for file [some_big_file.bak].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

GD: GoogleProxy  ERROR   There was an unhandled exception during the execution of the Drive logic for action [update_entry].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 734, in proxied_method
    return method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

GD: root         ERROR   There was an exception while invoking proxy action.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 794, in drive_proxy
    return method(auto_refresh, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 734, in proxied_method
    return method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

GD: OpenFile     ERROR   Could not localize displaced file with entry having ID [0ByhBU7ENwLxbMWU5OXRIUTJZMjA].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 515, in flush
    is_hidden=self.__is_hidden)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 794, in drive_proxy
    return method(auto_refresh, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 734, in proxied_method
    return method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

GD: FsUtility    ERROR   There was an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/fsutility.py", line 76, in wrapper
    result = f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 515, in flush
    is_hidden=self.__is_hidden)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 794, in drive_proxy
    return method(auto_refresh, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 734, in proxied_method
    return method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

GD: GD_VFS       ERROR   Could not flush local updates.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/gdfuse.py", line 468, in flush
    opened_file.flush()
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/fsutility.py", line 76, in wrapper
    result = f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdfs/opened_file.py", line 515, in flush
    is_hidden=self.__is_hidden)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 794, in drive_proxy
    return method(auto_refresh, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 734, in proxied_method
    return method(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/drive.py", line 618, in update_entry
    result = client.files().update(**args).execute()
  File "/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/apiclient/discovery.py", line 702, in method
    body = msgRoot.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/usr/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/usr/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 118, in _write
    self._fp.write(sfp.getvalue())
MemoryError

**Comment by seanmikhaels** [comment]
Hi Dsoprea, 

 Seems like i'm running into this issue as well on version 0.14.9 on raspberry PI 3. I'm not able to upload  large files, (  the file i'm trying to upload is 11GB ). i monitor the memory and eventually it only uploads about 720 MB, then grinds to a hault. I notice the free memory is 100% consumed along with the swap.
