### ISSUE TITLE
Error reading files larger than 512KB

### ISSUE THREAD

**Issue by karbowiak** [dsoprea/GDriveFS#81]
Hi.

I'm having an issue where uploading files larger than 512KB works great, but reading them back fails.

I can get the first 512KB of the file, and then it just errors out.
Below 512KB and it works great however.

Error logs:
gdrivefs with debug

```
$ gdfs /root/.gdfscache /mnt/gdfs -d
FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.22
flags=0x0000f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
# COPYING FILE UNDER 512KB
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 49, pid: 1845
LOOKUP /32kb.png
getattr /32kb.png
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: OPEN (14), nodeid: 2, insize: 48, pid: 1845
open flags: 0x8000 /32kb.png
   open[2] flags: 0x8000 /32kb.png
   unique: 3, success, outsize: 32
unique: 4, opcode: READ (15), nodeid: 2, insize: 80, pid: 1845
read[2] 32768 bytes from 0 flags: 0x8000
   read[2] 31793 bytes from 0
   unique: 4, success, outsize: 31809
unique: 5, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 1845
getattr /32kb.png
   unique: 5, success, outsize: 120
unique: 6, opcode: FLUSH (25), nodeid: 2, insize: 64, pid: 1845
flush[2]
   unique: 6, success, outsize: 16
unique: 7, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0
release[2] flags: 0x8000
   unique: 7, success, outsize: 16
# COPYING FILE OVER 512KB
unique: 8, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 1857
LOOKUP /Mining The EVE.pdf
getattr /Mining The EVE.pdf
   NODEID: 3
   unique: 8, success, outsize: 144
unique: 9, opcode: OPEN (14), nodeid: 3, insize: 48, pid: 1857
open flags: 0x8000 /Mining The EVE.pdf
   open[3] flags: 0x8000 /Mining The EVE.pdf
   unique: 9, success, outsize: 32
unique: 10, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 0 flags: 0x8000
   read[3] 131072 bytes from 0
   unique: 10, success, outsize: 131088
unique: 11, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 131072 flags: 0x8000
   read[3] 131072 bytes from 131072
   unique: 11, success, outsize: 131088
unique: 12, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 262144 flags: 0x8000
   read[3] 131072 bytes from 262144
   unique: 12, success, outsize: 131088
unique: 13, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 393216 flags: 0x8000
   read[3] 131072 bytes from 393216
   unique: 13, success, outsize: 131088
unique: 14, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 524288 flags: 0x8000
   read[3] 1 bytes from 524288
   unique: 14, success, outsize: 17
unique: 15, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 655360 flags: 0x8000
   unique: 15, error: -5 (Input/output error), outsize: 16
unique: 16, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 786432 flags: 0x8000
   unique: 16, error: -5 (Input/output error), outsize: 16
unique: 17, opcode: GETATTR (3), nodeid: 3, insize: 56, pid: 1857
getattr /Mining The EVE.pdf
   unique: 17, success, outsize: 120
unique: 18, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 524288 flags: 0x8000
   read[3] 1 bytes from 524288
   unique: 18, success, outsize: 17
unique: 19, opcode: READ (15), nodeid: 3, insize: 80, pid: 1857
read[3] 131072 bytes from 655360 flags: 0x8000
   unique: 19, error: -5 (Input/output error), outsize: 16
unique: 20, opcode: FLUSH (25), nodeid: 3, insize: 64, pid: 1857
flush[3]
   unique: 20, success, outsize: 16
unique: 21, opcode: RELEASE (18), nodeid: 3, insize: 64, pid: 0
release[3] flags: 0x8000
   unique: 21, success, outsize: 16
^C#       
```

gdrivefs.log

```
# COPYING FILE UNDER 512KB
# COPYING FILE OVER 512KB
2014-07-06 17:46:13,116 [FsUtility ERROR] There was an exception in [read]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (655360) exceeds length of data (524289).
2014-07-06 17:46:13,116 [gdrivefs.gdfs.gdfuse ERROR] Could not read data.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/gdfuse.py", line 243, in read
    return opened_file.read(offset, length)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (655360) exceeds length of data (524289).
2014-07-06 17:46:13,117 [FsUtility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [read]: [Errno 5] Input/output error
2014-07-06 17:46:13,117 [FsUtility ERROR] There was an exception in [read]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (786432) exceeds length of data (524289).
2014-07-06 17:46:13,117 [gdrivefs.gdfs.gdfuse ERROR] Could not read data.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/gdfuse.py", line 243, in read
    return opened_file.read(offset, length)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (786432) exceeds length of data (524289).
2014-07-06 17:46:13,117 [FsUtility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [read]: [Errno 5] Input/output error
2014-07-06 17:46:13,118 [FsUtility ERROR] There was an exception in [read]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (655360) exceeds length of data (524289).
2014-07-06 17:46:13,119 [gdrivefs.gdfs.gdfuse ERROR] Could not read data.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/gdfuse.py", line 243, in read
    return opened_file.read(offset, length)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/fsutility.py", line 77, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs-0.13.14-py2.7.egg/gdrivefs/gdfs/opened_file.py", line 585, in read
    (offset, buffer_len))
IndexError: Offset (655360) exceeds length of data (524289).
2014-07-06 17:46:13,119 [FsUtility ERROR] FUSE error [FuseOSError] (5) will be forwarded back to GDFS from [read]: [Errno 5] Input/output error
^C
```

Tried using the latest version from pip, and that was released, only thing i havn't tried is using the source repo, but i assume 0.13.14 is latest from the source repo.

**Comment by shauder** [comment]
I also get this problem
    root@debian:/mnt# cp /mnt/gdrive/www-data/big6.mp4 /home/shauder/
    cp: cannot open `/mnt/gdrive/www-data/big6.mp4' for reading: Input/output error

    root@debian:/mnt# pip search gdrivefs
    gdrivefs                  - A complete FUSE adapter for Google Drive.
    INSTALLED: 0.14.2 (latest)
    root@debian:/mnt# python
    Python 2.7.3 (default, Mar 13 2014, 11:03:55)
